# Generated by Django 5.1.15 on 2026-07-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('PRIMARY', 'Primary (KG–G12)'), ('UNIVERSITY', 'University'), ('HIGHER_ED', 'Higher education')], max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='catalog.vertical')),
            ],
            options={
                'ordering': ['vertical', 'order'],
                'unique_together': {('vertical', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_price_minor', models.IntegerField(help_text='Price charged to the student, in minor units')),
                ('teacher_wage_minor', models.IntegerField(help_text='Wage paid to the teacher, in minor units')),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_categories', to='catalog.gradelevel')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_categories', to='markets.market')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_categories', to='catalog.subject')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_categories', to='catalog.vertical')),
            ],
            options={
                'verbose_name_plural': 'Lesson categories',
                'unique_together': {('market', 'vertical', 'grade_level', 'subject')},
            },
        ),
    ]
