# Generated by Django 5.1.15 on 2026-08-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertical',
            name='child_kind',
            field=models.CharField(choices=[('NONE', 'No grouping (subjects directly)'), ('BRANCH', 'Branches'), ('FACULTY', 'Faculties')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='vertical',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.vertical')),
            ],
            options={
                'ordering': ['vertical', 'order'],
                'unique_together': {('vertical', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='StageSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_subjects', to='catalog.subject')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_subjects', to='catalog.vertical')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_subjects', to='catalog.track')),
            ],
            options={
                'ordering': ['vertical', 'track', 'order', 'subject'],
                'unique_together': {('vertical', 'track', 'subject')},
            },
        ),
    ]
