# Generated by Django 5.1.15 on 2026-09-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_stage_taxonomy'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_price_minor', models.IntegerField(help_text='Minimum lesson price a teacher may set, in minor units')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, help_text="Platform commission (0-100), deducted from the teacher's price", max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_pricing_rules', to='markets.market')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_pricing_rules', to='catalog.vertical')),
            ],
            options={
                'ordering': ['market', 'vertical'],
                'unique_together': {('market', 'vertical')},
            },
        ),
    ]
