# Generated by Django 5.1.15 on 2026-09-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stagepricingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncategory',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='lessoncategory',
            name='student_price_minor',
        ),
        migrations.RemoveField(
            model_name='lessoncategory',
            name='teacher_wage_minor',
        ),
    ]
