# Generated by Django 5.1.15 on 2026-09-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_lessoncategory_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='vertical',
            name='child_label_ar',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='vertical',
            name='child_label_en',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='child_kind',
            field=models.CharField(choices=[('NONE', 'No grouping (subjects directly)'), ('BRANCH', 'Branches'), ('FACULTY', 'Faculties'), ('GROUPED', 'Custom grouping (see child_label)')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='vertical',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional display-only header this stage appears under.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='catalog.stagegroup'),
        ),
    ]
