# Generated by Django 5.1.15 on 2026-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_stage_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagepricingrule',
            name='max_price_minor',
            field=models.IntegerField(blank=True, help_text='Maximum lesson price a teacher may set, in minor units; blank means no ceiling', null=True),
        ),
    ]
