# Generated by Django 5.1.15 on 2026-07-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('EG', 'Egypt'), ('SA', 'Saudi Arabia')], max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(help_text='ISO 4217, e.g. EGP / SAR', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BANK', 'Bank transfer'), ('WALLET', 'Mobile wallet')], max_length=10)),
                ('display_name', models.CharField(max_length=120)),
                ('details', models.TextField(help_text='Account number / IBAN / wallet number shown to students')),
                ('instructions', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='markets.market')),
            ],
            options={
                'ordering': ['market', 'sort_order'],
            },
        ),
    ]
