# Generated by Django 5.1.15 on 2026-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='code',
            field=models.CharField(choices=[('DZ', 'Algeria'), ('BH', 'Bahrain'), ('KM', 'Comoros'), ('DJ', 'Djibouti'), ('EG', 'Egypt'), ('IQ', 'Iraq'), ('JO', 'Jordan'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('LY', 'Libya'), ('MR', 'Mauritania'), ('MA', 'Morocco'), ('OM', 'Oman'), ('PS', 'Palestine'), ('QA', 'Qatar'), ('SA', 'Saudi Arabia'), ('SO', 'Somalia'), ('SD', 'Sudan'), ('SY', 'Syria'), ('TN', 'Tunisia'), ('AE', 'United Arab Emirates'), ('YE', 'Yemen')], max_length=2, unique=True),
        ),
    ]
