# Generated by Django 5.1.15 on 2026-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_favoriteteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
