# Generated by Django 5.1.15 on 2026-08-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_stage_taxonomy'),
        ('teachers', '0004_teacherprofile_certifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_specializations', to='catalog.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='teachers.teacherprofile')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_specializations', to='catalog.track')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_specializations', to='catalog.vertical')),
            ],
            options={
                'ordering': ['vertical', 'track', 'subject'],
                'unique_together': {('teacher', 'vertical', 'track', 'subject')},
            },
        ),
    ]
