# Generated by Django 5.1.15 on 2026-09-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_lessoncategory_currency_and_more'),
        ('teachers', '0007_teacherapplication_full_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='stage_prices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TeacherStagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_minor', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prices', to='teachers.teacherprofile')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_stage_prices', to='catalog.vertical')),
            ],
            options={
                'ordering': ['vertical'],
                'unique_together': {('teacher', 'vertical')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherPrice',
        ),
    ]
