# Generated by Django 5.1.15 on 2026-09-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_lessoncategory_currency_and_more'),
        ('teachers', '0008_teacherapplication_stage_prices_teacherstageprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TeacherStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_minor', models.IntegerField()),
                ('free_lessons_offered', models.PositiveSmallIntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='teachers.teacherprofile')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_stages', to='catalog.track')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_stages', to='catalog.vertical')),
            ],
            options={
                'ordering': ['vertical__order', 'track__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='teacher_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teachers.teacherstage'),
        ),
        migrations.CreateModel(
            name='TeacherStageSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_stage_subjects', to='catalog.subject')),
                ('teacher_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teachers.teacherstage')),
            ],
            options={
                'ordering': ['subject__name_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='teacherstage',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('teacher', 'vertical', 'track'), name='uniq_teacher_stage_track'),
        ),
        migrations.AddConstraint(
            model_name='teacherstage',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', True)), fields=('teacher', 'vertical'), name='uniq_teacher_stage_notrack'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstagesubject',
            unique_together={('teacher_stage', 'subject')},
        ),
    ]
