# Generated by Django 5.1.15 on 2026-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_backfill_stage_cards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherstageprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherstageprice',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherstageprice',
            name='vertical',
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='lesson_category',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='free_lessons_offered',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='stage_prices',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='free_lessons_offered',
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='teacher_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teachers.teacherstage'),
        ),
        migrations.DeleteModel(
            name='TeacherSpecialization',
        ),
        migrations.DeleteModel(
            name='TeacherStagePrice',
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
