# Generated by Django 5.1.15 on 2026-07-20 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_start', models.DateTimeField(help_text='Stored in UTC')),
                ('duration_min', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('NO_SHOW', 'No-show')], default='REQUESTED', max_length=12)),
                ('meeting_provider', models.CharField(blank=True, choices=[('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams'), ('CUSTOM', 'Custom link')], max_length=8)),
                ('meeting_link', models.URLField(blank=True)),
                ('price_minor', models.IntegerField()),
                ('teacher_wage_minor', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('is_trial', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.lessoncategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
    ]
