# Generated by Django 5.1.15 on 2026-07-25 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payout_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payouts.payoutitem'),
        ),
        migrations.AddField(
            model_name='booking',
            name='wage_settled',
            field=models.BooleanField(default=False),
        ),
    ]
