# Generated by Django 5.1.15 on 2026-09-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_payout_item_booking_wage_settled'),
        ('catalog', '0005_remove_lessoncategory_currency_and_more'),
        ('teachers', '0009_teacher_stage_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.subject'),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='teachers.teacherstage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.track'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vertical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.vertical'),
        ),
    ]
