# Generated by Django 5.1.15 on 2026-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_backfill_stage_snapshot'),
        ('catalog', '0005_remove_lessoncategory_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lesson_category',
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.subject'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.vertical'),
        ),
    ]
