# Generated by Django 5.1.15 on 2026-07-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('VERIFY', 'Verify'), ('RESET', 'Password reset')], default='LOGIN', max_length=10),
        ),
    ]
