# Generated by Django 5.1.15 on 2026-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('VERIFY', 'Verify'), ('RESET', 'Password reset')], default='VERIFY', max_length=10),
        ),
    ]
