# Generated by Django 5.1.15 on 2026-09-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_timezone'),
        ('catalog', '0005_remove_lessoncategory_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='catalog.vertical'),
        ),
    ]
