# Generated by Django 5.1.15 on 2026-07-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('student_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_threads', to='markets.market')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_threads', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.thread')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['student', '-last_message_at'], name='chat_thread_student_e787a8_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['teacher', '-last_message_at'], name='chat_thread_teacher_cdb707_idx'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('student', 'teacher'), name='uniq_thread_student_teacher'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', '-created_at'], name='chat_messag_thread__1fa440_idx'),
        ),
    ]
